heat_template_version: 2014-10-16

description: Template to deploy a server that creates a new metric and associate to Ceilometer

parameters:
  image:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
    default: Ubuntu-14-04-64
  flavor:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
    default: m1.medium
    constraints:
      - allowed_values: [m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge]
        description: instance_type must be a valid instance type
  key:
    type: string
    label: Key name
    description: Name of key-pair to be used for compute instance
    default: serranos

resources:

  test_server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      user_data: |
        #!/bin/sh -ex
        sudo apt-get update;
        sudo apt-get install -y build-essential python-dev python-pip python-oslo.config python-iso8601 git python-novaclient;
        sudo pip install tornado;
        sudo pip install msgpack-python;
        cd /home/ubuntu;
        git clone https://github.com/jyericlin/ceilometer-useragent.git;
        cd /home/ubuntu/ceilometer-useragent/;

        # Get resource id
        export OS_TENANT_NAME=ualberta;
        export OS_USERNAME=serranos;
        export OS_AUTH_URL=http://iam.savitestbed.ca:5000/v2.0;
        export OS_PASSWORD=Giba007G;
        export OS_REGION_NAME=CORE;
        export LOCAL_IP=$(ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}');
        export RESOURCE_ID=$(nova list | grep "$LOCAL_IP[ \|,]" | awk '{print $2}');

        # Install useragent
        export COLLECTOR_IP="10.10.60.10";
        export SECRET="bcaaa4b7-c95b-4583-bb9a-71d5e442ba35";
        export PROJECT_ID="1e70271ffe71433a91d9265c379177b7";
        export USER_ID="04f07e82c62a46e38975c1b3a8cea107";
        ./bin/install_useragent.sh $COLLECTOR_IP $SECRET $PROJECT_ID $USER_ID;

        # Useragent configuration
        echo "port=8888" | sudo tee -a /etc/ceilometer-useragent/ceilometer-useragent.conf;
        sudo sed -i 's@600000@60000@' /home/ubuntu/ceilometer-useragent/ceilometeruseragent/service.py;

        # Start useragent
        cd /home/ubuntu/ceilometer-useragent/bin;
        sudo ./start_useragent.sh;
        sleep 20;

        #Create test file
        cat > /home/ubuntu/stats <<EOL
        0          0          0          0          0             0          0          0          2          0          0     2015-07-21 17:52:40
        0          0          0          0          0             0          0          0          2          0          0     2015-07-21 17:52:43
        EOL

        # Create script for custom rule
        mkdir /home/ubuntu/rules;
        cd /home/ubuntu/rules;
        cat > rtpsessions.sh <<EOL
        #!/bin/bash
        FILENAME='/home/ubuntu/stats';
        SECOND_TO_LAST=\$(tail -2 \$FILENAME | head -1);
        SECOND_TO_LAST=\$(sed -e 's/^[[:space:]]*//' <<< \$SECOND_TO_LAST);
        LAST=\$(tail -n1 \$FILENAME);
        LAST=\$(sed -e 's/^[[:space:]]*//' <<< \$LAST);

        if [[ \${LAST:0:3} = 'RTP' ]];
        then echo \$SECOND_TO_LAST | awk '{print \$1}';
        else echo \$LAST | awk '{print \$1}';
        fi;
        EOL
        chmod +x rtpsessions.sh;

        # Create custom rule
        cd /home/ubuntu/ceilometer-useragent/bin;
        ./add_rules.sh rtpsessions gauge U $RESOURCE_ID 'Shell Script' "/home/ubuntu/rules/rtpsessions.sh";
      user_data_format: RAW

outputs:
  instance_name:
    description: Name of the instance
    value: { get_attr: [test_server, name] }
